# -*- coding: utf-8 -*-
"""
买入卖出推荐逻辑审查
检查评分系统和信号生成逻辑
"""
import sys
sys.stdout.reconfigure(encoding='utf-8')

print("=" * 70)
print("买入卖出推荐逻辑审查")
print("=" * 70)

print("\n【问题1】预测目标分析:")
print("  目标定义: rise_3d >= 0.03 (未来3日涨幅>=3%)")
print("  pred[1]: 预测'未来3日涨幅>=3%'的概率")
print("  ")
print("  当前逻辑:")
print("    pred[1] > 0.6 → 买入（涨幅>=3%概率高）")
print("    pred[1] < 0.3 → 卖出（涨幅>=3%概率低）")
print("    0.3-0.6 → 持有")
print("  ")
print("  ❌ 问题:")
print("    '涨幅>=3%概率低' ≠ '应该卖出'")
print("    卖出应该代表'跌幅>=3%概率高'，而不是'涨幅概率低'")

print("\n【问题2】评分计算:")
print("  当前: score = int(pred[1] * 100)")
print("  ")
print("  买入时 (pred[1] > 0.6):")
print("    score范围: 60-100 ✅")
print("  ")
print("  卖出时 (pred[1] < 0.3):")
print("    score范围: 0-29 ❌")
print("    问题: score应该反映卖出置信度，而不是涨幅概率")

print("\n【问题3】买入卖出筛选:")
print("  当前逻辑:")
print("    buy_list: action == '买入' and score >= 60")
print("    sell_list: action == '卖出'")
print("  ")
print("  问题:")
print("    买入筛选的 score >= 60 是冗余条件")
print("    卖出筛选没有置信度要求")

print("\n【正确逻辑建议】:")
print("  ")
print("  方案1（双模型）:")
print("    - 买入模型: 预测 rise_3d >= 0.03")
print("    - 卖出模型: 预测 fall_3d >= 0.03 (跌幅>=3%)")
print("    - 买入信号: buy_prob > 0.6")
print("    - 卖出信号: sell_prob > 0.6")
print("  ")
print("  方案2（单模型改进）:")
print("    - 预测未来3日涨跌幅")
print("    - 买入信号: 预测涨幅>=3%")
print("    - 卖出信号: 预测跌幅>=3%")
print("  ")
print("  方案3（当前改进）:")
print("    - 买入: pred[1] > 0.6 (涨幅>=3%概率>60%)")
print("    - 卖出: pred[1] < 0.15 (涨幅>=3%概率<15%，即跌幅概率>85%)")
print("    - 持有: 0.15-0.6")

print("\n【评分改进建议】:")
print("  ")
print("  买入评分 (pred[1] > 0.6):")
print("    score = int(pred[1] * 100)  # 60-100")
print("  ")
print("  卖出评分 (pred[1] < 0.15):")
print("    sell_confidence = 1 - pred[1]  # 跌幅概率")
print("    score = int(sell_confidence * 100)  # 85-100")
print("  ")
print("  持有评分 (0.15-0.6):")
print("    score = 50  # 中性")

print("\n" + "=" * 70)
print("审查完成")
print("=" * 70)